export const trails = [
    {
        "id": 31804,
        "state":"Colorado",
        "city":"Idaho Springs",
        "name": "Centennial Cone",
        "summary": "One of the better beginner/intermediate rides in the front range.",
        "difficulty": "blue",
        "stars": 4.1,
        "starVotes": 310,
        "location": "Idaho Springs, Colorado",
        "url": "https://www.mtbproject.com/trail/31804/centennial-cone",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7029901_sqsmall_1555016067.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7029901_small_1555016067.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7029901_smallMed_1555016067.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7029901_medium_1555016067.jpg",
        "length": 17.2,
        "ascent": 2340,
        "descent": -2348,
        "high": 7911,
        "low": 6804,
        "longitude": -105.371,
        "latitude": 39.7372,
        "conditionStatus": "Minor Issues",
        "conditionDetails": "Muddy, Snowy - Some mud and snow on trail under the evergreens but the vast majority of Loop is dry.",
        "conditionDate": "2019-10-12 22:21:43"
    },
    {
        "id": 46286,
        "state":"Colorado",
        "city":"Boulder",
        "name": "Betasso Preserve",
        "summary": "A solid ride close to Boulder that is often ridden from town.",
        "difficulty": "greenBlue",
        "stars": 4,
        "starVotes": 247,
        "location": "Boulder, Colorado",
        "url": "https://www.mtbproject.com/trail/46286/betasso-preserve",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7002944_sqsmall_1554403854.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7002944_small_1554403854.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7002944_smallMed_1554403854.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7002944_medium_1554403854.jpg",
        "length": 7.4,
        "ascent": 829,
        "descent": -829,
        "high": 6589,
        "low": 6178,
        "longitude": -105.3422,
        "latitude": 40.0155,
        "conditionStatus": "All Clear",
        "conditionDetails": "Dry - Perfect after a little rain",
        "conditionDate": "2019-10-03 22:57:25"
    },
    {
        "id": 7000620,
        "state":"Colorado",
        "name": "Apex Park Tour",
        "summary": "This technical front range ride is only possible on even numbered days but it's worth the planning!",
        "difficulty": "blueBlack",
        "stars": 4.4,
        "starVotes": 169,
        "location": "West Pleasant View, Colorado",
        "city":"West Pleasant View",
        "url": "https://www.mtbproject.com/trail/7000620/apex-park-tour",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7018020_sqsmall_1554917670.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7018020_small_1554917670.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7018020_smallMed_1554917670.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7018020_medium_1554917670.jpg",
        "length": 9.4,
        "ascent": 1668,
        "descent": -1667,
        "high": 7309,
        "low": 6164,
        "longitude": -105.2097,
        "latitude": 39.7162,
        "conditionStatus": "Minor Issues",
        "conditionDetails": "Some Mud",
        "conditionDate": "2019-10-02 14:51:31"
    },
    {
        "id": 43824,
        "state":"Colorado",
        "name": "Hall Ranch",
        "summary": "A favorite for Boulder area riders - scenery, singletrack, technical sections...  it's got it all!",
        "difficulty": "blueBlack",
        "stars": 4.5,
        "starVotes": 245,
        "location": "Lyons, Colorado",
        "city":"Lyons",
        "url": "https://www.mtbproject.com/trail/43824/hall-ranch",
        "imgSqSmall": "https://img.youtube.com/vi/hI1RUEer4ng/hqdefault.jpg",
        "imgSmall": "https://img.youtube.com/vi/hI1RUEer4ng/hqdefault.jpg",
        "imgSmallMed": "https://img.youtube.com/vi/hI1RUEer4ng/hqdefault.jpg",
        "imgMedium": "https://img.youtube.com/vi/hI1RUEer4ng/hqdefault.jpg",
        "length": 11.8,
        "ascent": 1750,
        "descent": -1750,
        "high": 6679,
        "low": 5464,
        "longitude": -105.2884,
        "latitude": 40.2106,
        "conditionStatus": "All Clear",
        "conditionDetails": "Dry",
        "conditionDate": "2019-09-19 07:53:12"
    },
    {
        "id": 5466724,
        "state":"Colorado",
        "name": "North Table Loop",
        "summary": "Big climbs. Rowdy descents. Amazing 360-degree views.",
        "difficulty": "blue",
        "stars": 3.7,
        "starVotes": 230,
        "location": "Golden, Colorado",
        "city":"Golden",
        "url": "https://www.mtbproject.com/trail/5466724/north-table-loop",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7010776_sqsmall_1554838463.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7010776_small_1554838463.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7010776_smallMed_1554838463.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7010776_medium_1554838463.jpg",
        "length": 7.5,
        "ascent": 883,
        "descent": -934,
        "high": 6482,
        "low": 5857,
        "longitude": -105.2301,
        "latitude": 39.7812,
        "conditionStatus": "All Clear",
        "conditionDetails": "Dry",
        "conditionDate": "2019-08-18 11:14:29"
    },
    {
        "id": 4683982,
        "state": "Georgia",
        "name": "Big Creek Park",
        "summary": "A great urban trail system in the city of Roswell - a bike friendly community. Maintained by RAMBO.",
        "difficulty": "blue",
        "stars": 4,
        "starVotes": 52,
        "location": "Roswell, Georgia",
        "city":"Roswell",
        "url": "https://www.mtbproject.com/trail/4683982/big-creek-park",
        "imgSqSmall": "https://img.youtube.com/vi/Cew7xyEGJgs/hqdefault.jpg",
        "imgSmall": "https://img.youtube.com/vi/Cew7xyEGJgs/hqdefault.jpg",
        "imgSmallMed": "https://img.youtube.com/vi/Cew7xyEGJgs/hqdefault.jpg",
        "imgMedium": "https://img.youtube.com/vi/Cew7xyEGJgs/hqdefault.jpg",
        "length": 7.7,
        "ascent": 549,
        "descent": -549,
        "high": 1072,
        "low": 955,
        "longitude": -84.3122,
        "latitude": 34.0244,
        "conditionStatus": "Unknown",
        "conditionDetails": null,
        "conditionDate": "1970-01-01 00:00:00"
    },
    {
        "id": 7021394,
        "state": "Georgia",
        "name": "All-A-Toona Loop",
        "summary": "This route is great training for the annual All-A-Toona Race!",
        "difficulty": "blue",
        "stars": 4.5,
        "starVotes": 22,
        "location": "Acworth, Georgia",
        "city":"Acworth",
        "url": "https://www.mtbproject.com/trail/7021394/all-a-toona-loop",
        "imgSqSmall": "https://img.youtube.com/vi/w2IRwUYqqRs/hqdefault.jpg",
        "imgSmall": "https://img.youtube.com/vi/w2IRwUYqqRs/hqdefault.jpg",
        "imgSmallMed": "https://img.youtube.com/vi/w2IRwUYqqRs/hqdefault.jpg",
        "imgMedium": "https://img.youtube.com/vi/w2IRwUYqqRs/hqdefault.jpg",
        "length": 31.6,
        "ascent": 2178,
        "descent": -2203,
        "high": 998,
        "low": 851,
        "longitude": -84.7181,
        "latitude": 34.0209,
        "conditionStatus": "Minor Issues",
        "conditionDetails": "Mostly Dry: Always check http://sorbawestgeorgia.org/ for trail conditions (opened/closed) before heading to the park.",
        "conditionDate": "2019-08-26 14:52:33"
    },
    {
        "id": 7012793,
        "state": "Georgia",
        "name": "Dirty Sheets Gravel Loop",
        "summary": "This loop provides an escape from Atlanta traffic to grind some gravel!",
        "difficulty": "greenBlue",
        "stars": 4.6,
        "starVotes": 18,
        "location": "Chattahoochee Hills, Georgia",
        "city":"Chattahoochee Hills",
        "url": "https://www.mtbproject.com/trail/7012793/dirty-sheets-gravel-loop",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7009007_sqsmall_1554829898.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7009007_small_1554829898.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7009007_smallMed_1554829898.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7009007_medium_1554829898.jpg",
        "length": 20.7,
        "ascent": 916,
        "descent": -919,
        "high": 1005,
        "low": 741,
        "longitude": -84.7133,
        "latitude": 33.5713,
        "conditionStatus": "All Clear",
        "conditionDetails": "",
        "conditionDate": "2019-10-11 22:41:35"
    },
    {
        "id": 7000133,
        "state": "Georgia",
        "name": "Georgia International Horse Park",
        "summary": "A great trail set on the iconic site of the 1996 Olympic mountain bike race course.",
        "difficulty": "blue",
        "stars": 4.1,
        "starVotes": 28,
        "location": "Conyers, Georgia",
        "city":"Conyers",
        "url": "https://www.mtbproject.com/trail/7000133/georgia-international-horse-park",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7019803_sqsmall_1554925728.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7019803_small_1554925728.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7019803_smallMed_1554925728.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7019803_medium_1554925728.jpg",
        "length": 8.9,
        "ascent": 991,
        "descent": -995,
        "high": 813,
        "low": 659,
        "longitude": -83.9422,
        "latitude": 33.6722,
        "conditionStatus": "Bad / Closed",
        "conditionDetails": "Trails will be closed from September 27 until October 9 for the Atlanta Spartan Race.",
        "conditionDate": "2019-09-05 21:25:40"
    },
    {
        "id": 7000612,
        "state": "Georgia",
        "name": "Mt. Tabor Park",
        "summary": "A tour of the stacked loop system on offer at Mt. Tabor Park.",
        "difficulty": "greenBlue",
        "stars": 3.6,
        "starVotes": 12,
        "location": "Hiram, Georgia",
        "city":"Hiram",
        "url": "https://www.mtbproject.com/trail/7000612/mt-tabor-park",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7005553_sqsmall_1554823711.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7005553_small_1554823711.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7005553_smallMed_1554823711.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7005553_medium_1554823711.jpg",
        "length": 4.7,
        "ascent": 276,
        "descent": -288,
        "high": 1161,
        "low": 1048,
        "longitude": -84.7711,
        "latitude": 33.9464,
        "conditionStatus": "Unknown",
        "conditionDetails": null,
        "conditionDate": "1970-01-01 00:00:00"
    },
    {
        "id": 340491,
        "state": "Georgia",
        "name": "Cunningham Park",
        "summary": "Fast singletrack and dirt jumping awesomeness, ranging from absolute beginners to skilled XC/FR.",
        "difficulty": "blueBlack",
        "stars": 4.2,
        "starVotes": 27,
        "location": "Bellerose Terrace, New York",
        "city":"Bellerose Terrace",
        "state":"New York",
        "url": "https://www.mtbproject.com/trail/340491/cunningham-park",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/342625_small_1554220646.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/342625_medium_1554220646.jpg",
        "length": 4.4,
        "ascent": 202,
        "descent": -205,
        "high": 100,
        "low": 57,
        "longitude": -73.7652,
        "latitude": 40.7422,
    },
    {
        "id": 7000490,
        "state":"New York",
        "name": "Sprain Ridge Loop",
        "summary": "A great loop close to the city that includes technical climbs, rollers, drops, and descents.",
        "difficulty": "blueBlack",
        "stars": 4,
        "starVotes": 23,
        "location": "Ardsley, New York",
        "city":"Ardsley",
        "url": "https://www.mtbproject.com/trail/7000490/sprain-ridge-loop",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/7027367_sqsmall_1555010863.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/7027367_small_1555010863.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/7027367_smallMed_1555010863.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/7027367_medium_1555010863.jpg",
        "length": 7.6,
        "ascent": 855,
        "descent": -842,
        "high": 381,
        "low": 138,
        "longitude": -73.8492,
        "latitude": 40.9855,
        "conditionStatus": "Minor Issues",
        "conditionDetails": "Dry - tracks aren't well indicated",
        "conditionDate": "2019-09-21 12:58:47"
    },
    {
        "id": 7000959,
        "state":"New York",
        "name": "Frost Woods Park",
        "summary": "A good local ride, LOTS of small trails in a rather small area.",
        "difficulty": "greenBlue",
        "stars": 2.3,
        "starVotes": 3,
        "location": "Spotswood, New Jersey",
        "city":"Spotswood",
        "url": "https://www.mtbproject.com/trail/7000959/frost-woods-park",
        "imgSqSmall": "",
        "imgSmall": "",
        "imgSmallMed": "",
        "imgMedium": "",
        "length": 5.2,
        "ascent": 245,
        "descent": -245,
        "high": 130,
        "low": 63,
        "longitude": -74.3893,
        "latitude": 40.4086,
        "conditionStatus": "Unknown",
        "conditionDetails": null,
        "conditionDate": "1970-01-01 00:00:00"
    },
    {
        "id": 7038214,
        "state":"New York",
        "name": "Many Log Run",
        "summary": "Nice flowy section with log obstacles.",
        "difficulty": "blueBlack",
        "stars": 5,
        "starVotes": 2,
        "location": "Navesink, New Jersey",
        "city":"Navesink",
        "url": "https://www.mtbproject.com/trail/7038214/many-log-run",
        "imgSqSmall": "",
        "imgSmall": "",
        "imgSmallMed": "",
        "imgMedium": "",
        "length": 1.3,
        "ascent": 76,
        "descent": -113,
        "high": 168,
        "low": 89,
        "longitude": -74.0414,
        "latitude": 40.3876,
        "conditionStatus": "Unknown",
        "conditionDetails": null,
        "conditionDate": "1970-01-01 00:00:00"
    },
    {
        "id": 348093,
        "state":"New York",
        "name": "Green Apple",
        "summary": "Singletrack with some technical areas.",
        "difficulty": "blueBlack",
        "stars": 5,
        "starVotes": 2,
        "location": "Bellerose Terrace, New York",
        "city":"Bellerose Terrace",
        "url": "https://www.mtbproject.com/trail/348093/green-apple",
        "imgSqSmall": "https://cdn-files.apstatic.com/mtb/342625_sqsmall_1554220646.jpg",
        "imgSmall": "https://cdn-files.apstatic.com/mtb/342625_small_1554220646.jpg",
        "imgSmallMed": "https://cdn-files.apstatic.com/mtb/342625_smallMed_1554220646.jpg",
        "imgMedium": "https://cdn-files.apstatic.com/mtb/342625_medium_1554220646.jpg",
        "length": 1,
        "ascent": 27,
        "descent": -34,
        "high": 92,
        "low": 76,
        "longitude": -73.7708,
        "latitude": 40.74,
        "conditionStatus": "Unknown",
        "conditionDetails": null,
        "conditionDate": "1970-01-01 00:00:00"
    },
]